#!/bin/bash
mkdir /judge
cd /judge || exit
curl -L https://github.com/int-y1/judge-server/archive/refs/heads/fix-go.tar.gz | tar -xz --strip-components=1
python3 -m venv --prompt=DMOJ env
env/bin/pip3 install -e .
runuser -u judge -w PATH -- bash -c '. ~/.profile; /judge/env/bin/python3 -u .docker.test.py'
